### ISSUE TITLE
Frontend: Version Control and View from Application

### ISSUE THREAD

**Issue by pojojojo21** [Griddle-Assets/griddle-asset-db#37]

**Comment by kyraSclark** [comment]
Each version should be downloaded to a different folder. The infrastructure doesn't seem to support this currently. It only makes a folder on initial asset creation. There's a lot of changes that need to happen to make this feature.

**Comment by kyraSclark** [comment]
Yeah, I did a lot of research and testing with the downloads store, which is what I was asking about before. However, I do not think it works as expected. Somehow, the store has become very bloated, and it wasn't going to work for this system, which is why I resorted to the JSON implementation. I agree with your comment though; I like the JSON system because it *should* make other features easier (like, indicating whether or not files where changed using file hashing for example).
